/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import static Views.ConsultarNotas.buildTableModel;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import oracle.jdbc.OracleTypes;
import registrofia.OracleConnection;

/**
 *
 * @author anderson
 */
public class InscribirAsignaturas extends javax.swing.JFrame {

    /**
     * Creates new form InscribirAsignaturas
     */
    public InscribirAsignaturas() {
        initComponents();
        String str = OracleConnection.getUsr();
        jTextField1.setText(str);
        
        Connection conn = null;
        ResultSet rs = null;
        OracleConnection c = new OracleConnection();

        try {
            conn = c.getConnection();
            String sql = "BEGIN basenotas.sp_h_materias_inscripciones(?,?); END;";

            CallableStatement sp;
            sp = conn.prepareCall(sql);
            
            sp.registerOutParameter(1, OracleTypes.CURSOR);
            sp.setString(2, str);
            sp.execute();
            
            rs = (ResultSet) sp.getObject(1);

            // si el while termina y b = 0 el alumno no posee materias que pueda inscribir
            Integer b = 0;
            while (rs.next()) {
                if (rs.getString("disponible").equalsIgnoreCase("si")) {
                    b = 1;
                    jComboBox1.addItem(rs.getString("codigo_asignatura"));
                }
            }
            if (b == 0) {
                jComboBox1.setEnabled(false);
                JOptionPane.showMessageDialog(null, "El alumno " + str
                        + " no posee materias que pueda inscribir", "Error", JOptionPane.ERROR_MESSAGE);
            }
            rs.close();
            sp.close();
            conn.close();
        } catch (Exception e) {
            // handle the exception
            e.printStackTrace();
            System.err.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscribir Materias");

        jLabel1.setText("Carnet:");

        jTextField1.setEnabled(false);

        jButton1.setText("Ver asignaturas cursadas durante el ciclo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Asignaturas disponibles:");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("Inscribir materia");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(jTextField1))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        OracleConnection oc = new OracleConnection();
        Connection conn = null;
        //Statement stmt = null;
        ResultSet rs = null;
        
        try {
            conn = oc.getConnection();
            
            String query = "BEGIN basenotas.sp_h_materias_recuperar(?,?); END;";
            CallableStatement cs;
            cs = conn.prepareCall(query);
            
            cs.setString(2, OracleConnection.getUsr());
            cs.registerOutParameter(1, OracleTypes.CURSOR);
            
            cs.execute();
            
            rs = (ResultSet)cs.getObject(1);
            
            // It creates and displays the table
            JTable table = new JTable(buildTableModel(rs));
            table.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            JOptionPane.showMessageDialog(null, new JScrollPane(table, 
                    JScrollPane.VERTICAL_SCROLLBAR_ALWAYS, 
                    JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS), "estudiante@" 
                    + OracleConnection.getUsr(), JOptionPane.PLAIN_MESSAGE);
        } catch (Exception e) {
            // handle the exception
            e.printStackTrace();
            System.err.println(e.getMessage());
        } finally {
            try {
                rs.close();
                //stmt.close();
                conn.close();
            } catch (Exception ee) {
                ee.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Connection conn = null;
        OracleConnection c = new OracleConnection();
        String usr = OracleConnection.getUsr();
        Calendar now = Calendar.getInstance();
        
        if (jComboBox1.getItemCount() != 0) {
            // tiene materias para inscribir
            String codigo_asignatura = jComboBox1.getSelectedItem().toString();
            Integer num_expediente = 0;
            float nota_final = 0;
            String estado = "en curso";
            Integer matricula = 1;
            Integer year_ciclo = now.get(Calendar.YEAR);
            Integer ciclo = 0;
            try {
                conn = c.getConnection();
                String sql = "BEGIN basenotas.SP_EXPEDIENTE_RECUPERAR(?,?); END;";
                
                CallableStatement sp;
                sp = conn.prepareCall(sql);
                
                sp.setString(1, usr);
                sp.registerOutParameter(2, OracleTypes.CURSOR);
                sp.execute();
                
                //Se obtiene el cursor en forma de ResultSet
                ResultSet rs = (ResultSet) sp.getObject(2);
                
                while (rs.next()) {
                    num_expediente = Integer.parseInt(rs.getString("num_expediente"));
                    //System.out.println(num_expediente);
                }
                rs.close();
                sp.close();
                
                sql = "BEGIN basenotas.SP_H_MATERIAS_INSERT(?,?,?,?,?,?,?); END;";
                sp = conn.prepareCall(sql);
                
                sp.setString(1, codigo_asignatura);
                sp.setInt(2, num_expediente);
                sp.setFloat(3, nota_final);
                sp.setInt(4, matricula);
                sp.setString(5, estado);
                sp.setInt(6, year_ciclo);
                sp.setInt(7, ciclo);
                
                System.out.println("*" + codigo_asignatura+"*"+num_expediente+"*"+
                        nota_final+"*"+matricula+"*"+estado+"*"+year_ciclo+"*"+ciclo+"*");
                
                sp.execute();
                
                JOptionPane.showMessageDialog(null, "¡¡ Materia inscrita exitosamente !!");
                jComboBox1.removeItem(codigo_asignatura);
                
                if(jComboBox1.getItemCount() == 0){
                    jComboBox1.setEditable(false);
                    jButton2.setEnabled(false);
                }
                
                rs.close();
                sp.close();
                conn.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        } else {
            // no tiene materias que pueda inscribir
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InscribirAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InscribirAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InscribirAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InscribirAsignaturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InscribirAsignaturas().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
