/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oracle.jdbc.OracleCallableStatement;
import oracle.jdbc.OracleTypes;
import registrofia.OracleConnection;

/**
 *
 * @author Dell i3
 */
public class Update_Asignatura extends javax.swing.JFrame {
    /**
     * Creates new form Nueva_Asignatura
     */
    CallableStatement cstm = null;
    ResultSet rset = null; 
    public Update_Asignatura() {
        initComponents();
          setLocationRelativeTo(null);
        llenarcombo1();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        des = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        obj = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        uv = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        bib = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        rec_tec = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        otro = new javax.swing.JTextArea();
        jScrollPane7 = new javax.swing.JScrollPane();
        rec_lab = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        perfil = new javax.swing.JTextArea();
        Actualizar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jus = new javax.swing.JTextArea();
        jScrollPane11 = new javax.swing.JScrollPane();
        gen = new javax.swing.JTextArea();
        codigo = new javax.swing.JComboBox();
        volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Crear Asignatura");

        jLabel1.setText("Codigo");

        jLabel2.setText("Nombre");

        jLabel3.setText("Generalidades");

        jLabel4.setText("Descripcion");

        des.setColumns(20);
        des.setRows(5);
        jScrollPane2.setViewportView(des);

        jLabel5.setText("Objetivo");

        obj.setColumns(20);
        obj.setRows(5);
        jScrollPane3.setViewportView(obj);

        jLabel6.setText("UV");

        uv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                uvKeyTyped(evt);
            }
        });

        jLabel7.setText("Bibliografia");

        bib.setColumns(20);
        bib.setRows(5);
        jScrollPane4.setViewportView(bib);

        jLabel8.setText("Recursos Laboratorio");

        jLabel9.setText("Recursos Tecnologicos");

        jLabel10.setText("Otros Recursos");

        rec_tec.setColumns(20);
        rec_tec.setRows(5);
        jScrollPane5.setViewportView(rec_tec);

        otro.setColumns(20);
        otro.setRows(5);
        jScrollPane6.setViewportView(otro);

        rec_lab.setColumns(20);
        rec_lab.setRows(5);
        jScrollPane7.setViewportView(rec_lab);

        jLabel11.setText("Perfil Docente");

        perfil.setColumns(20);
        perfil.setRows(5);
        jScrollPane8.setViewportView(perfil);

        Actualizar.setText("Actualizar");
        Actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActualizarActionPerformed(evt);
            }
        });

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        jLabel12.setText("Justificacion");

        jus.setColumns(20);
        jus.setRows(5);
        jScrollPane9.setViewportView(jus);

        gen.setColumns(20);
        gen.setRows(5);
        jScrollPane11.setViewportView(gen);

        codigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Seleccione Opcion" }));
        codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigoActionPerformed(evt);
            }
        });

        volver.setText("Volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(Actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cancelar)
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                            .addComponent(jScrollPane6))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jScrollPane8))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(55, 55, 55)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(uv, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(214, 214, 214)))
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5)
                                    .addComponent(jScrollPane3)
                                    .addComponent(jScrollPane9)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(volver))
                                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE))))))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(volver))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(uv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Actualizar)
                    .addComponent(cancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActualizarActionPerformed
        String cod=(String)codigo.getSelectedItem();
        if(nom.getText().equals("") || cod.equals("Seleccion Opcion") || uv.getText().equals("") || gen.getText().equals("") || des.getText().equals("") || 
          obj.getText().equals("") || bib.getText().equals("") || rec_lab.getText().equals("") || rec_tec.getText().equals("") || 
          otro.getText().equals("") || perfil.getText().equals("") || jus.getText().equals("")){
           JOptionPane.showMessageDialog(null, "No puede dejar campos vacios", "Error en los datos", JOptionPane.ERROR_MESSAGE);
       }
       else{
                Connection cn = null;
                OracleConnection c = new OracleConnection();
                
                try{
                    cn= c.getConnectionDocente();
                    cstm = cn.prepareCall("begin tareabase.sp_asignatura_update(?,?,?,?,?,?,?,?,?,?,?,?,?,?);end;");
                    cstm.setString(1,(String)codigo.getSelectedItem());
                    cstm.setString(2,nom.getText());
                    cstm.setString(3,gen.getText());
                    cstm.setString(4,des.getText());
                    cstm.setString(5,obj.getText());
                    int u=Integer.parseInt(uv.getText());
                    cstm.setInt(6,u);
                    cstm.setString(7,bib.getText());
                    cstm.setString(8,jus.getText());
                    cstm.setString(9,rec_lab.getText());
                    cstm.setString(10,rec_tec.getText());
                    cstm.setString(11,otro.getText());
                    cstm.setString(12,perfil.getText());
                    cstm.setInt(13,1);
                    cstm.setInt(14,1);
                    cstm.execute();
                    cstm.close();
                    cn.close();
                }
                catch (SQLException se){
                     do {
                         System.out.println("SQL STATE: " + se.getSQLState());
                         System.out.println("ERROR CODE: " + se.getErrorCode());
                         System.out.println("MESSAGE: " + se.getMessage());
                         System.out.println();
                         se =se.getNextException();
                        } while (se != null);
           
                } catch (Exception ex) {
                Logger.getLogger(Update_Asignatura.class.getName()).log(Level.SEVERE, null, ex);
            }
            }  
    }//GEN-LAST:event_ActualizarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
System.exit( 0 );         
// TODO add your handling code here:
    }//GEN-LAST:event_cancelarActionPerformed

    private void codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigoActionPerformed
       Connection cn = null;
       OracleConnection c = new OracleConnection();
        try{
           cn= c.getConnectionDocente();
           cstm = cn.prepareCall("begin tareabase.CURSORES.Obtener_asignatura(?,?);end;");
           cstm.setString(1,(String)codigo.getSelectedItem());
           cstm.registerOutParameter(2,OracleTypes.CURSOR);
            cstm.execute();
                rset =((OracleCallableStatement) cstm).getCursor(2);
                while (rset.next()){
                     String nombr=rset.getString(2);
                     String gene=rset.getString(3);
                     String descri=rset.getString(4);
                     String obje=rset.getString(5);
                     String bibli=rset.getString(7);
                     String justi=rset.getString(8);
                     String re_lab=rset.getString(9);
                     String re_te=rset.getString(10);
                     String re_ot=rset.getString(11);
                     String perf=rset.getString(12);
                     nom.setText(nombr);
                     gen.setText(gene);
                     des.setText(descri);
                     obj.setText(obje);
                     String unival=Integer.toString(rset.getInt(6));
                     uv.setText(unival);
                     bib.setText(bibli);
                     jus.setText(justi);
                     rec_lab.setText(re_lab);
                     rec_tec.setText(re_te);
                     otro.setText(re_ot);
                     perfil.setText(perf);
                }
                
                rset.close();
                cstm.close();
                cn.close();
       }
        catch (SQLException se){
                     do {
                         System.out.println("SQL STATE: " + se.getSQLState());
                         System.out.println("ERROR CODE: " + se.getErrorCode());
                         System.out.println("MESSAGE: " + se.getMessage());
                         System.out.println();
                         se =se.getNextException();
                        } while (se != null);
           
                } catch (Exception ex) {
            Logger.getLogger(Update_Asignatura.class.getName()).log(Level.SEVERE, null, ex);
        // TODO add your handling code here:
                }
    }//GEN-LAST:event_codigoActionPerformed

    private void uvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_uvKeyTyped
        int k = (int) evt.getKeyChar();
if (k >= 97 && k <= 122 || k >= 65 && k <= 90) {

evt.consume();
JOptionPane.showMessageDialog(null, "No puede ingresar letras", "Error", JOptionPane.ERROR_MESSAGE);
}
        // TODO add your handling code here:
    }//GEN-LAST:event_uvKeyTyped

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        menudocente jFrame= new menudocente();
        jFrame.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Asignatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Asignatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Actualizar;
    private javax.swing.JTextArea bib;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox codigo;
    private javax.swing.JTextArea des;
    private javax.swing.JTextArea gen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextArea jus;
    private javax.swing.JTextField nom;
    private javax.swing.JTextArea obj;
    private javax.swing.JTextArea otro;
    private javax.swing.JTextArea perfil;
    private javax.swing.JTextArea rec_lab;
    private javax.swing.JTextArea rec_tec;
    private javax.swing.JTextField uv;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables
public void llenarcombo1(){
            Connection cn = null;
            OracleConnection c = new OracleConnection();
            try {
                cn= c.getConnectionDocente();
                cstm = cn.prepareCall("begin tareabase.CURSORES.OBTENER_DATOS(?,?);end;");
                String dui= "12345";
                cstm.setString(1,dui);
                cstm.registerOutParameter(2, OracleTypes.CURSOR);
                cstm.execute();
                rset =((OracleCallableStatement) cstm).getCursor(2);
                while (rset.next()){
                     String dato=rset.getString(1);
                     String estado=rset.getString(2);
                    if("activo".equals(estado))
                        codigo.addItem(dato);
                }
                rset.close();
                cstm.close();
                cn.close();
            }
            catch (SQLException se){
                do {
                    System.out.println("SQL STATE: " + se.getSQLState());
                    System.out.println("ERROR CODE: " + se.getErrorCode());
                    System.out.println("MESSAGE: " + se.getMessage());
                    System.out.println();
                    se = se.getNextException();
                } while (se != null);
            } catch (Exception ex) {
            Logger.getLogger(Update_Asignatura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
