
-- INSERTA LOS DATOS HISTORIAL DOCENTE //GEOVA

create sequence ID_HISTORIAL_DOCENTE
start with 1
increment by 1;

create or replace procedure sp_hist_docente_insert
(
    DUIDOCENTE HISTORIAL_DOCENTE.DUI%TYPE,
    CODIGO_ASIG HISTORIAL_DOCENTE.CODIGO_ASIGNATURA%TYPE
)
IS
BEGIN
    INSERT INTO HISTORIAL_DOCENTE(ID_CORRELATIVO,DUI,CODIGO_ASIGNATURA,ESTADO_IMPARTE,FECHA_INICIO) 
    VALUES(Id_historial_docente.nextval,DUIDOCENTE,CODIGO_ASIG,'Activo',sysdate);
END sp_hist_docente_insert;



-- actualiza los datos del docente //GEOVA

CREATE OR REPLACE PROCEDURE sp_hist_docente_update
(
    DUIDOCENTE HISTORIAL_DOCENTE.DUI%TYPE,
    CODIGO HISTORIAL_DOCENTE.CODIGO_ASIGNATURA%TYPE
)
IS
BEGIN
    UPDATE HISTORIAL_DOCENTE HD
    SET HD.ESTADO_IMPARTE='inactivo',HD.FECHA_FIN=sysdate
    WHERE HD.DUI=DUIDOCENTE AND HD.CODIGO_ASIGNATURA=CODIGO;
END sp_hist_docente_update;


