
create or replace procedure insertar_historial_docente
(
DUIDOCENTE HISTORIAL_DOCENTE.DUI%TYPE,
CODIGO_ASIG HISTORIAL_DOCENTE.CODIGO_ASIGNATURA%TYPE,
ESTADO HISTORIAL_DOCENTE.ESTADO_IMPARTE%TYPE,
FECHA1 DATE,FECHA2 DATE)
IS
BEGIN
INSERT INTO HISTORIAL_DOCENTE(ID_CORRELATIVO,DUI,CODIGO_ASIGNATURA,ESTADO_IMPARTE,FECHA_INICIO,
FECHA_FIN) VALUES(Id_historial_docente.nextval,DUIDOCENTE,CODIGO_ASIG,ESTADO,FECHA1,FECHA2);
END;



-- actualiza los datos del docente

CREATE OR REPLACE PROCEDURE UPDATE_HISTORIAL_DOCENTE
(
DUIDOCENTE HISTORIAL_DOCENTE.DUI%TYPE,
CODIGO HISTORIAL_DOCENTE.CODIGO_ASIGNATURA%TYPE,
FECHA1 DATE)
IS
BEGIN
UPDATE HISTORIAL_DOCENTE HD
SET HDESTADO_IMPARTE='inactivo',HD.FECHA_FIN=FECHA1
WHERE HD.DUI=DUIDOCENTE AND HD.CODIGO_ASIGNATURA=CODIGO;
END UPDATE_HISTORIAL_DOCENTE;


